import type { DemoAccount, Goal, Task, KPI, Notification, TeamMember } from "@/types";

export const DEMO_ACCOUNTS: DemoAccount[] = [
  {
    role: "individual",
    label: "Individual User",
    email: "teams@propelaxis.com",
    password: "123456",
    description: "Personal goal tracking & KPI management",
    icon: "User",
    color: "from-green-500 to-green-600",
  },
  {
    role: "team",
    label: "Team Organization",
    email: "org@propelaxis.com",
    password: "123456",
    description: "Team collaboration & department analytics",
    icon: "Users",
    color: "from-indigo-500 to-indigo-600",
  },
  {
    role: "coach",
    label: "Coach / Mentor",
    email: "coach@propelaxis.com",
    password: "123456",
    description: "Client progress tracking & coaching plans",
    icon: "Award",
    color: "from-emerald-500 to-emerald-600",
  },
  {
    role: "educational",
    label: "Educational Institution",
    email: "edu@propelaxis.com",
    password: "123456",
    description: "Student progress & academic goal management",
    icon: "BookOpen",
    color: "from-amber-500 to-amber-600",
  },
  {
    role: "enterprise",
    label: "Enterprise Client",
    email: "enterprise@propelaxis.com",
    password: "123456",
    description: "Multi-team analytics & enterprise reporting",
    icon: "Building2",
    color: "from-rose-500 to-rose-600",
  },
  {
    role: "admin",
    label: "Admin",
    email: "admin@propelaxis.com",
    password: "123456",
    description: "Platform administration & user management",
    icon: "Shield",
    color: "from-slate-700 to-slate-800",
  },
];

export const MOCK_GOALS: Goal[] = [
  {
    id: "1",
    title: "Increase Revenue by 30%",
    description: "Drive revenue growth through new client acquisition and upselling",
    category: "Financial",
    status: "active",
    progress: 68,
    deadline: "2026-06-30",
    createdAt: "2026-01-15",
    ownerId: "user1",
    priority: "high",
  },
  {
    id: "2",
    title: "Launch Mobile App",
    description: "Complete development and launch the mobile application",
    category: "Product",
    status: "active",
    progress: 45,
    deadline: "2026-05-15",
    createdAt: "2026-01-10",
    ownerId: "user1",
    priority: "high",
  },
  {
    id: "3",
    title: "Expand Team by 5 Members",
    description: "Hire and onboard 5 new team members across departments",
    category: "HR",
    status: "completed",
    progress: 100,
    deadline: "2026-03-31",
    createdAt: "2026-01-05",
    ownerId: "user1",
    priority: "medium",
  },
  {
    id: "4",
    title: "Improve NPS Score to 70",
    description: "Enhance customer satisfaction and support processes",
    category: "Customer",
    status: "at-risk",
    progress: 35,
    deadline: "2026-04-30",
    createdAt: "2026-01-20",
    ownerId: "user1",
    priority: "high",
  },
  {
    id: "5",
    title: "Complete Leadership Training",
    description: "Finish executive leadership development program",
    category: "Learning",
    status: "active",
    progress: 72,
    deadline: "2026-05-30",
    createdAt: "2026-02-01",
    ownerId: "user1",
    priority: "medium",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: "Review Q1 performance metrics",
    status: "completed",
    priority: "high",
    dueDate: "2026-04-02",
    createdAt: "2026-03-25",
    goalId: "1",
  },
  {
    id: "t2",
    title: "Prepare investor presentation",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-04-10",
    createdAt: "2026-04-01",
    goalId: "1",
  },
  {
    id: "t3",
    title: "Finalize app UI wireframes",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-04-08",
    createdAt: "2026-04-01",
    goalId: "2",
  },
  {
    id: "t4",
    title: "Set up CI/CD pipeline",
    status: "todo",
    priority: "medium",
    dueDate: "2026-04-15",
    createdAt: "2026-04-02",
    goalId: "2",
  },
  {
    id: "t5",
    title: "Conduct customer interviews",
    status: "todo",
    priority: "high",
    dueDate: "2026-04-12",
    createdAt: "2026-04-02",
    goalId: "4",
  },
  {
    id: "t6",
    title: "Update documentation",
    status: "todo",
    priority: "low",
    dueDate: "2026-04-20",
    createdAt: "2026-04-03",
  },
];

export const MOCK_KPIS: KPI[] = [
  {
    id: "k1",
    name: "Monthly Revenue",
    current: 124500,
    target: 150000,
    unit: "$",
    trend: "up",
    change: 12.4,
    category: "Financial",
  },
  {
    id: "k2",
    name: "Goal Completion Rate",
    current: 78,
    target: 90,
    unit: "%",
    trend: "up",
    change: 5.2,
    category: "Performance",
  },
  {
    id: "k3",
    name: "Team Productivity",
    current: 85,
    target: 95,
    unit: "%",
    trend: "stable",
    change: 0.8,
    category: "Operations",
  },
  {
    id: "k4",
    name: "Customer NPS",
    current: 62,
    target: 70,
    unit: "pts",
    trend: "up",
    change: 4,
    category: "Customer",
  },
  {
    id: "k5",
    name: "Task Completion",
    current: 142,
    target: 180,
    unit: "tasks",
    trend: "up",
    change: 18,
    category: "Operations",
  },
  {
    id: "k6",
    name: "Active Users",
    current: 2847,
    target: 3500,
    unit: "users",
    trend: "up",
    change: 9.3,
    category: "Growth",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    title: "Goal milestone reached",
    message: "You have completed 70% of your Revenue Growth goal.",
    type: "success",
    read: false,
    createdAt: "2026-04-08T09:30:00Z",
  },
  {
    id: "n2",
    title: "Task overdue",
    message: "Customer interview task is due today.",
    type: "warning",
    read: false,
    createdAt: "2026-04-08T08:15:00Z",
  },
  {
    id: "n3",
    title: "New team member added",
    message: "Sarah Chen has joined the Product team.",
    type: "info",
    read: true,
    createdAt: "2026-04-07T14:00:00Z",
  },
  {
    id: "n4",
    title: "KPI alert",
    message: "Customer NPS score dropped below target threshold.",
    type: "error",
    read: false,
    createdAt: "2026-04-07T11:30:00Z",
  },
  {
    id: "n5",
    title: "Weekly report ready",
    message: "Your weekly performance report for W14 is now available.",
    type: "info",
    read: true,
    createdAt: "2026-04-06T09:00:00Z",
  },
];

export const MOCK_TEAM: TeamMember[] = [
  {
    id: "tm1",
    name: "Sarah Chen",
    email: "sarah@propelaxis.com",
    role: "Product Manager",
    department: "Product",
    performance: 92,
    status: "active",
  },
  {
    id: "tm2",
    name: "Marcus Johnson",
    email: "marcus@propelaxis.com",
    role: "Lead Engineer",
    department: "Engineering",
    performance: 88,
    status: "active",
  },
  {
    id: "tm3",
    name: "Elena Rodriguez",
    email: "elena@propelaxis.com",
    role: "Design Lead",
    department: "Design",
    performance: 95,
    status: "active",
  },
  {
    id: "tm4",
    name: "David Kim",
    email: "david@propelaxis.com",
    role: "Sales Director",
    department: "Sales",
    performance: 74,
    status: "active",
  },
  {
    id: "tm5",
    name: "Priya Patel",
    email: "priya@propelaxis.com",
    role: "Data Analyst",
    department: "Analytics",
    performance: 81,
    status: "inactive",
  },
];

export const NAV_LINKS = [
  { label: "Home", path: "/" },
  { label: "About", path: "/about" },
  { label: "Features", path: "/features" },
  { label: "Solutions", path: "/solutions" },
  { label: "Pricing", path: "/pricing" },
  { label: "Resources", path: "/resources" },
  { label: "Contact", path: "/contact" },
];

export const CHART_DATA_MONTHLY = [
  { month: "Jan", goals: 12, tasks: 48, kpis: 8 },
  { month: "Feb", goals: 18, tasks: 65, kpis: 11 },
  { month: "Mar", goals: 22, tasks: 72, kpis: 14 },
  { month: "Apr", goals: 28, tasks: 89, kpis: 18 },
  { month: "May", goals: 25, tasks: 94, kpis: 16 },
  { month: "Jun", goals: 35, tasks: 110, kpis: 22 },
  { month: "Jul", goals: 40, tasks: 128, kpis: 26 },
  { month: "Aug", goals: 38, tasks: 142, kpis: 29 },
  { month: "Sep", goals: 45, tasks: 158, kpis: 33 },
  { month: "Oct", goals: 52, tasks: 171, kpis: 38 },
  { month: "Nov", goals: 48, tasks: 185, kpis: 41 },
  { month: "Dec", goals: 60, tasks: 200, kpis: 45 },
];

export const PERFORMANCE_DATA = [
  { name: "Week 1", performance: 62 },
  { name: "Week 2", performance: 71 },
  { name: "Week 3", performance: 68 },
  { name: "Week 4", performance: 78 },
  { name: "Week 5", performance: 82 },
  { name: "Week 6", performance: 88 },
  { name: "Week 7", performance: 85 },
  { name: "Week 8", performance: 91 },
];

export const KPI_DISTRIBUTION = [
  { name: "Financial", value: 35, color: "#3b82f6" },
  { name: "Operations", value: 28, color: "#8b5cf6" },
  { name: "Customer", value: 22, color: "#10b981" },
  { name: "Growth", value: 15, color: "#f59e0b" },
];
